### ISSUE TITLE
Link back to rustc's notes on static compiling

### ISSUE THREAD

**Issue by gurgalex** [Michael-F-Bryan/rust-ffi-guide#10]
Is there a way to add an anchor to these [notes](https://github.com/Michael-F-Bryan/rust-ffi-guide/blame/e6a07b872e52598cd323c05344270be10a2ae325/src/arrays/index.md#L135)?

Sample thought process:
1.  Do you remember those notes?  Me:  No? what notes?
2.  (Sees that 'notes' is clickable) clicks on link
3.  Me:  Oh, those notes! (reads them over again)
4.  Is there a way to go back to where I clicked from?

The way it is currently:
1.  Do you remember those notes?  Me: No? what notes?
2.  (Sees no link to notes), hopes that it wasn't too important
3.  Or, spends lots of time searching for a mention of notes.

**Comment by Michael-F-Bryan** [comment]
Markdown allows you to add normal HTML links and anchors, so you should be able to an empty HTML tag which you can then set a link to. 

So you could do this in the `src/introduction/index.md`:

```md
/* contents of intro page */
...

<span id="notes-gcc"></span>
There are much more elegant solutions than this, but it'll suffice for now.
```

Then later on you add a link to it like this:

```md
Do you remember when we said there's an [easier way]? Well there is, it's called gcc-rs. 

[easier way]: introduction/index.html#notes-gcc
```
