### ISSUE TITLE
Create an error handling chapter

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Michael-F-Bryan/rust-ffi-guide#22]
Error handling is a pretty important thing to get right when you are doing FFI stuff. In particular you need to make sure not to accidentally let Rust panics cross the FFI barrier because then bad things happen. 

Another thing to think about is that error handling is done very differently in different languages. For example, C often uses the "out params" pattern with a return code to signal errors, whereas Python, Java, and friends use exceptions. When making a Rust library which is called from other languages, it might be a good idea to copy C's way of error handling and then any non-C language bindings can wrap that and use whatever is idiomatic for that language.

---

Some questions to investigate:

- What is a good example which would display error handling without being excessively long?
- What is the "idiomatic" way to represent errors? A C-style enum where the `0` variant is the equivalent of `Ok(...)`?
- Is wrapping calls with `panic::catch_unwind()` and then returning an error if a panic occurred the best way of handling things?

@gurgalex, can you think of anything we should include in a chapter on error handling?

**Comment by gurgalex** [comment]
Not at the moment. (My knowledge of Rust and C is currently limited)

**Comment by gurgalex** [comment]
I can provide some possible questions / comments to be addressed.
// Is it assumed that the audience has ever used / heard of a Foreign Function Interface (FFI) ?
1. How is the caller of the foreign function notified that an error has occurred? (formatting,  error information / cause)  Code examples may be helpful.
2.  Python and the `cffi` module were used to allow calling foreign functions. 
How are error codes documented?  How is the documentation presented?
Would a team member have to read the program's docs? Or, would the docs show up in say an IDE tooltip? (Foo produces exit code 1 = <filename> not found)

**Comment by Michael-F-Bryan** [comment]
I wrote up a quick example which just opens a file and then tries to write its contents into a buffer provided by C ([playground link]). 

I've been going through most of this tutorial assuming that the user is fairly familiar with Rust and knows a bit of C. If they don't already know C then they're going to find it quite hard to understand things as FFI is a bit more of an advanced concept. 

I'm also trying to do things from the perspective of someone trying to integrate some Rust code into an existing C/C++ codebase because that's effectively what I'm doing at work.

Regarding documentation, I'd typically document the `ErrorCode` enum (the thing used in my example) explicitly saying what each variant stands for (e.g. `ErrorCode::NullPointer` means you passed in a null pointer) and then in functions which may return an error you might have an `# Errors` section in the rust docs which explains which errors might occur.

Regarding IDE and documentation stuff, I've written a small tool which parses your Rust code, looks for things which are  `#[no_mangle]` and `pub extern "C"`, then generates C-style header files with the corresponding declarations. The tool preserves doc comments, so all documentation present in the Rust version should be present in the generated header file, which your IDE will read and can then make sure to show you a useful tooltip.

[playground link]: https://play.rust-lang.org/?gist=34dc733293495f6b6821c345ada18820&version=stable
