### ISSUE TITLE
ctypes missing link

### ISSUE THREAD

**Issue by gurgalex** [Michael-F-Bryan/rust-ffi-guide#23]
Did you want a link to ctype's [docs](https://docs.python.org/3/library/ctypes.html)?[
No link reference](https://github.com/Michael-F-Bryan/rust-ffi-guide/blame/fc055b5974e8e1b3b39ebc9e91571e9b250370bb/src/pythonic/index.md#L119)

**Comment by gurgalex** [comment]
Updated issue to note that ctypes is missing a link.

**Comment by Michael-F-Bryan** [comment]
Oops! Looks like I forgot to put in a `[ctypes]: https://docs.python.org/3/library/ctypes.html` at the bottom. Would you be able to fix that when you are rewording the Python section?

**Comment by gurgalex** [comment]
Yeah, I can add that as another commit.

**Comment by pravic** [comment]
The same for cffi - it's just a `[cffi][cffi]` now.

**Comment by gurgalex** [comment]
Added as another commit. Thanks, @pravic !
