### ISSUE TITLE
Pythonic section

### ISSUE THREAD

**Issue by pravic** [Michael-F-Bryan/rust-ffi-guide#25]
```python
    def __iter__(self):
        running = True
        while running:
            prime = self.next()
            yield prime
            running = prime != 0
```

Is there any reason to yield `0`? I think, it was intended to indicate the end of sequence.

**Comment by Michael-F-Bryan** [comment]
Yeah, the `0` is meant to signify that there are no more primes. In reality `self.next()` should probably throw something like `StopIteration` instead. Does that sound logical to you?

**Comment by pravic** [comment]
I am not sure, but it seems we can either raise an exception or just return None here.

**Comment by gurgalex** [comment]
What about
```Python
class Primes:
    def __enter__(self):
        self.iterator = primal.primes_new()
        return self

    def __exit__(self, *args):
        primal.primes_destroy(self.iterator)

    def __next__(self):
    // Get the next prime
            prime = primal.primes_next(self.iterator)
    // Raise StopIteration if the next prime is zero (no more primes!)
            if prime == 0:
                raise StopIteration
    // Otherwise return the next prime
            return prime

    def __iter__(self):
        return self
```

**Comment by gurgalex** [comment]
Or, here's a generator version
```Python
class Primes:
    def __enter__(self):
        self.iterator = primal.primes_new()
        return self

    def __exit__(self, *args):
        primal.primes_destroy(self.iterator)

    def next(self):
        return primal.primes_next(self.iterator)

    def __iter__(self):
        while True:
            prime = self.next()
            if prime == 0:
                raise StopIteration
            yield prime
```

**Comment by gurgalex** [comment]
Would it be less confusing to get rid of `def next(self):`?
Replacing `prime = self.next()` with `prime = primal.primes_next(self.iterator)`
Or, is that too much on one line?

Before Python 3, `__next__` was named `next`

**Comment by Michael-F-Bryan** [comment]
I think the first snippet is better, it feels the most idiomatic and easier to understand once you know how `for` loops work. The `__next__` vs `next` difference is probably not very relevant because nobody should be using Python 2 any more.

@gurgalex or @pravic, would either of you like to try to do this? Otherwise I'll make a PR when I get home.

**Comment by gurgalex** [comment]
Turns out the generator code I posted doesn't need to have StopIteration raised.
It'll be raised whenever the function `__iter__` stops yielding.
```Python
class Primes:
    def __enter__(self):
        self.iterator = primal.primes_new()
        return self

    def __exit__(self, *args):
        primal.primes_destroy(self.iterator)

    def __iter__(self):
        prime = primal.primes_next(self.iterator)
        while prime != 0:
            yield prime
            prime = primal.primes_next(self.iterator)
```

The example still produces the same output if `Primes` is turned into the function `primes()`
```Python
def primes():

    iterator = primal.primes_new()

    prime = primal.primes_next(iterator)
    while prime != 0:
        yield prime
        prime = primal.primes_next(iterator)

    primal.primes_destroy(iterator)
```
Although, some renaming must be done.  Plus, I believe the `with Primes as p` can be replaced by assigning to a variable.
```Python
    p = primes()
    n = 20
    first_20 = list(itertools.islice(p, n))
    print(first_20)
```

**Comment by gurgalex** [comment]
Although, `Primes` may have been a class so that the `__enter__` and `__exit__` methods can be called.  It'll also be useable with the `with` keyword.  
It'll also ensure that even if an error occurs, that `__exit__` gets called to cleanup.

**Comment by pravic** [comment]
> Plus, I believe the  with Primes as p  can be replaced by assigning to a variable.
Nope. In case of unexpected exception we can leak primal's handle, so it's better to support the `with` context statement.

**Comment by gurgalex** [comment]
Thanks, thought of that shortly after posting as well.
