### ISSUE TITLE
Usage of personal voice

### ISSUE THREAD

**Issue by skade** [Michael-F-Bryan/rust-ffi-guide#3]
(Not sure if "personal voice" is the correct term, I'm not a native english speaker)

During reading, it occured to me that sometimes, especially at the beginning, the book drops into your personal voice and describes things in terms of "I'll be using...". While that style fits a short guide written by one author, it makes it a little harder to contributed and - at least to me - not very assertive. It's what you did or do, but doesn't sound like a generally good thing.

Would you be interested in changing that? In that case, I'd be willing to make the changes as a way to get used to editing the book.

**Comment by Michael-F-Bryan** [comment]
You raise a good point. Using personal voice is good for short tutorials or blog posts, but considering this is more targeted to be an extended guide which multiple people contribute towards (similar to [The Book][book] and the [nomicon][nom]) I should probably change the use of personal voice.

If you want to make edits then I'd be more than happy to accept pull requests. Editing the book isn't overly difficult, they're essentially just markdown files and viewing the rendered document is just a case of running `mdbook serve` (make sure you install [mdbook][mdbook] - `cargo install mdbook`).

Let me know if you are interested in contributing or have any issues or feedback.

[book]: https://doc.rust-lang.org/stable/book/
[nom]: https://doc.rust-lang.org/nomicon/
[mdbook]: https://github.com/azerupi/mdBook

**Comment by skade** [comment]
Hi Michael,

Thanks for the reply. I am indeed interested and will work through the book and see what I can help out with.

Florian
