### ISSUE TITLE
CC0 License

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Michael-F-Bryan/rust-ffi-guide#55]
The Rust Cookbook are in the process of changing their license (rust-lang-nursery/rust-cookbook#209) from MIT/Apache to [CC0]. The idea is that this guide should be copied freely with no restrictions, so it's probably a good idea to follow suit.

@gurgalex, are you okay with this?

[CC0]: https://creativecommons.org/choose/zero/

**Comment by gurgalex** [comment]
Fine by me.
