### ISSUE TITLE
Make the book more consistent

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Michael-F-Bryan/rust-ffi-guide#8]
Bits and pieces of this book were written in the first person, while others have been written in the third person. To the book more consistent and easier for others to contribute to, all usage of the first person point-of-view should be converted to third person.

The easiest way to find what to fix is to grep all markdown files for common first person phrases (like " I ").

(Hint: `grep -E " I | I'm | me | my " $(find . -name '*.md')`)

---

Progress so far:

- [ ] [README](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/README.md)
- [x] [Introduction](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/introduction/index.md)
- [x] [Arrays](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/arrays/index.md)
- [x] [Structs](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/structs/index.md)
- [x] [Strings](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/strings/index.md)
- [x] [Bindgen](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/bindgen/index.md)
- [ ] [Pythonic](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/pythonic/index.md) One instance left.
- [x] [Dynamic Loading](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/dynamic_loading/index.md)
- [x] [Callbacks](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/callbacks/index.md)
- [ ] [Best Practices](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/best_practices.md) One instance left.

**Comment by Michael-F-Bryan** [comment]
@gurgalex [mentioned] in one of the PRs associated with this issue:

> Even the second edition of the Rust book uses we'll. It does sound more less demanding than you'll. We'll sounds like the book (or the author) is there to help you. While you'll sounds like you're on your own.
Another benefit of we'll is that it sometimes flows better, and uses less words.
>
>So, the task of rewording first person usage could be limited to situations that aren't inclusive of the reader (my, I)

I think we should rephrase the scope of this issue to mean "reword the book to be inclusive of the reader (we/our) instead of using language that excludes the reader (I/me)".

@gurgalex, how does that sound?

[mentioned]: https://github.com/Michael-F-Bryan/rust-ffi-guide/pull/21#discussion_r131842884

**Comment by gurgalex** [comment]
I agree. My reasons are in the text you quoted above.

**Comment by Michael-F-Bryan** [comment]
@gurgalex, how far through this issue do you think we are? Can you make a [checklist] which has all the current chapters, then tick off the chapters we've already merged PRs for? 

Once we have a checklist, I'll add it to the issue description so we can tell at a glance where we're at and what still needs to be done.

Once again, thanks a lot for all the work you've done towards this! It's really appreciated.

[checklist]: https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments

**Comment by gurgalex** [comment]
Here is the current state of the book on removing or rewording statements that only include the author (I / my)
- [ ] [README](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/README.md)
- [x] [Introduction](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/introduction/index.md)
- [x] [Arrays](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/arrays/index.md)
- [x] [Structs](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/structs/index.md)
- [x] [Strings](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/strings/index.md)
- [x] [Bindgen](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/bindgen/index.md)
- [ ] [Pythonic](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/pythonic/index.md) One instance left.
- [x] [Dynamic Loading](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/dynamic_loading/index.md)
- [x] [Callbacks](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/callbacks/index.md)
- [ ] [Best Practices](https://github.com/Michael-F-Bryan/rust-ffi-guide/blob/master/src/best_practices.md) One instance left.

Based on the output of the grep command `grep -E " I | I'm | me | my " $(find . -name '*.md')`
```
./README.md:rendered version is automatically rendered every time I push a commit and is
./README.md:If there's anything you want me to add or you notice something which might need
./src/best_practices.md:please, please, please [create an issue][issue] and let me know!
./src/pythonic/index.md:this example I'm going to try and build a *pythonic* interface to the amazing
./src/strings/index.md:"how do I deallocate this once I'm done?". For this, the docs provide:
./src/introduction/index.md:    let me = CString::new("World").unwrap();
```

**Comment by gurgalex** [comment]
All usages of non-inclusive first person from the grep script are removed.
So, I think this can be closed.
Unless, this is an ongoing task for the other chapters as well.

**Comment by Michael-F-Bryan** [comment]
Thank you for everything you've done towards this @gurgalex, what you've done has been really phenomenal! It might have taken about a dozen PRs spread over 80 commits, but now the book sounds so much better and has received the TLC it deserves.

**Comment by gurgalex** [comment]
Sounds like a great idea! 😄 
I didn't know that some languages had ways to work with others besides C.
Plus, we may get more suggestions for how to improve the book further.
